// src/renderer/src/components/MarkedItemsView.svelte
<script lang="ts">
  import type { MarkedItem } from '../types';

  let {
    markedItems,
    onEdit,
    onDelete
  }: {
    markedItems: MarkedItem[];
    onEdit: (item: MarkedItem) => void;
    onDelete: (id: string) => void;
  } = $props();

  let filterQuery = $state('');

  const filteredItems = $derived(
    markedItems.filter((item) =>
      item.from.toLowerCase().includes(filterQuery.toLowerCase())
    )
  );

</script>

<div class="p-2 border-b border-line bg-panel3/10 flex items-center gap-2 shrink-0">
  <svg class="w-3.5 h-3.5 text-ink-dim ml-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
  </svg>
  <input
    type="text"
    bind:value={filterQuery}
    placeholder="Filter items..."
    class="bg-transparent text-ink text-[11px] font-mono outline-none w-full h-5 placeholder:text-ink-dim/50 uppercase tracking-tighter"
  />
  {#if filterQuery}
    <button onclick={() => filterQuery = ''} class="text-ink-dim hover:text-ink p-1">
      <svg class="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
      </svg>
    </button>
  {/if}
</div>

<div class="grid grid-cols-[1fr_140px_120px] gap-0 border-b border-line bg-panel3/30 font-mono text-[10px] text-ink-dim uppercase tracking-widest shrink-0">
  <div class="p-3 truncate">FROM MATCH</div>
  <div class="p-3">MARK</div>
  <div class="p-3 text-right">ACTION</div>
</div>

<div class="flex-1 overflow-y-auto overflow-x-hidden relative">
  {#if filteredItems.length === 0}
    <div class="absolute inset-0 flex items-center justify-center text-ink-dim font-mono text-[10px]">
      {filterQuery ? 'NO_MATCHING_ITEMS' : 'NO_MARKED_ITEMS'}
    </div>
  {:else}
    {#each filteredItems as item (item.id)}
      <div class="grid grid-cols-[1fr_140px_120px] gap-0 border-b border-line text-sm hover:bg-panel2/50">
        <div class="p-3 truncate text-ink/90">{item.from}</div>
        <div class="p-3 font-mono text-[11px] uppercase {item.action === 'archive' ? 'text-brand' : 'text-danger'}">{item.action === 'archive' ? 'Archive' : 'Delete'}</div>
        <div class="p-2 flex justify-end gap-2">
          <button onclick={() => onEdit(item)} class="px-2 py-1 rounded bg-panel3 text-ink-dim hover:text-ink font-mono text-[10px] uppercase">Edit</button>
          <button onclick={() => onDelete(item.id)} class="px-2 py-1 rounded bg-danger/10 text-danger hover:bg-danger/20 font-mono text-[10px] uppercase">Drop</button>
        </div>
      </div>
    {/each}
  {/if}
</div>

// src/renderer/src/components/MarkedItemsView.tsx
import { useMemo, useState } from 'react'
import type { MarkedItem } from '../types'
export default function MarkedItemsView({
  markedItems,
  onEdit,
  onDelete
}: {
  markedItems: MarkedItem[]
  onEdit: (item: MarkedItem) => void
  onDelete: (id: string) => void
}) {
  const [query, setQuery] = useState('')
  const items = useMemo(
    () => markedItems.filter((i) => i.from.toLowerCase().includes(query.toLowerCase())),
    [markedItems, query]
  )
  return (
    <>
      <div className="flex shrink-0 items-center gap-2 border-b border-line bg-panel3/10 p-2">
        <span className="ml-1 text-ink-dim">⌕</span>
        <input
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Filter items..."
          className="h-5 w-full bg-transparent font-mono text-[11px] uppercase tracking-tighter text-ink outline-none"
        />
        {query && (
          <button onClick={() => setQuery('')} className="p-1 text-ink-dim">
            ×
          </button>
        )}
      </div>
      <div className="grid shrink-0 grid-cols-[1fr_140px_120px] border-b border-line bg-panel3/30 font-mono text-[10px] uppercase tracking-widest text-ink-dim">
        <div className="p-3">FROM MATCH</div>
        <div className="p-3">MARK</div>
        <div className="p-3 text-right">ACTION</div>
      </div>
      <div className="relative flex-1 overflow-y-auto">
        {items.length === 0 ? (
          <div className="absolute inset-0 flex items-center justify-center font-mono text-[10px] text-ink-dim">
            {query ? 'NO_MATCHING_ITEMS' : 'NO_MARKED_ITEMS'}
          </div>
        ) : (
          items.map((item) => (
            <div
              key={item.id}
              className="grid grid-cols-[1fr_140px_120px] border-b border-line text-sm hover:bg-panel2/50"
            >
              <div className="truncate p-3 text-ink/90">{item.from}</div>
              <div
                className={`p-3 font-mono text-[11px] uppercase ${item.action === 'archive' ? 'text-brand' : 'text-danger'}`}
              >
                {item.action === 'archive' ? 'Archive' : 'Delete'}
              </div>
              <div className="flex justify-end gap-2 p-2">
                <button
                  onClick={() => onEdit(item)}
                  className="rounded bg-panel3 px-2 py-1 font-mono text-[10px] uppercase text-ink-dim"
                >
                  Edit
                </button>
                <button
                  onClick={() => onDelete(item.id)}
                  className="rounded bg-danger/10 px-2 py-1 font-mono text-[10px] uppercase text-danger"
                >
                  Drop
                </button>
              </div>
            </div>
          ))
        )}
      </div>
    </>
  )
}
