// src/renderer/src/components/StagingBins.tsx
// Staging: two named bins so Archive and Delete never mix, one dense line per sender
// (bar length = count), a hover peek that tracks the line, and an explicit put-back
// control. Click a line to keep its peek open while inspecting the messages.
import { useMemo, useState } from 'react'
import type { EmailMsg, MarkAction, MarkedItem } from '../types'
import { senderAddr, senderName } from '../lib/sender'

type Line = { key: string; from: string; msgs: EmailMsg[]; byRule: boolean }

type Props = {
  emails: EmailMsg[]
  marks: Record<string, MarkAction>
  rules: MarkedItem[]
  busy?: boolean
  onunmark: (ids: string[]) => void
  onunmarkall: () => void
  onapply: () => void
}

export default function StagingBins({
  emails,
  marks,
  rules,
  busy = false,
  onunmark,
  onunmarkall,
  onapply
}: Props) {
  const [hover, setHover] = useState<string | null>(null)
  const [pinned, setPinned] = useState<string | null>(null)
  const [peekExpanded, setPeekExpanded] = useState(false)
  const [hoverY, setHoverY] = useState(0)

  const ruleFor = (from: string) =>
    rules.find(
      (rule) => rule.from.trim() && from.toLowerCase().includes(rule.from.trim().toLowerCase())
    )
  const linesFor = (action: MarkAction): Line[] => {
    const by = new Map<string, Line>()
    for (const message of emails) {
      if (marks[message.id] !== action) continue
      const key = senderAddr(message.from)
      if (!by.has(key)) {
        by.set(key, {
          key,
          from: message.from,
          msgs: [],
          byRule: Boolean(ruleFor(message.from))
        })
      }
      by.get(key)!.msgs.push(message)
    }
    return [...by.values()].sort((a, b) => b.msgs.length - a.msgs.length)
  }

  const archive = useMemo(() => linesFor('archive'), [emails, marks, rules])
  const trash = useMemo(() => linesFor('trash'), [emails, marks, rules])
  const total = Object.keys(marks).length
  const count = (lines: Line[]) => lines.reduce((number, line) => number + line.msgs.length, 0)
  const hovered = useMemo(() => {
    const lines = [...archive, ...trash]
    const pinnedLine = pinned
      ? lines.find((line) => line.key + ':' + marks[line.msgs[0].id] === pinned)
      : undefined
    const key = pinnedLine ? pinned : hover
    return lines.find((line) => line.key + ':' + marks[line.msgs[0].id] === key)
  }, [archive, trash, marks, pinned, hover])

  const peek = (event: React.MouseEvent<HTMLElement>, key: string) => {
    if (!pinned && hover !== key) setPeekExpanded(false)
    setHover(key)
    if (!pinned) setHoverY(event.currentTarget.getBoundingClientRect().top)
  }

  const pinPeek = (element: HTMLElement, key: string) => {
    setHover(key)
    setHoverY(element.getBoundingClientRect().top)
    if (pinned === key) {
      setPinned(null)
      setPeekExpanded(false)
      return
    }
    setPinned(key)
    setPeekExpanded(false)
  }

  const closePeek = () => {
    setPinned(null)
    setHover(null)
    setPeekExpanded(false)
  }

  const renderBin = (title: string, action: MarkAction, lines: Line[]) => {
    const isArchive = action === 'archive'
    const dotClass = isArchive ? 'bg-brand' : 'bg-danger'
    const labelClass = isArchive ? 'text-brand' : 'text-danger'
    return (
      <div className="flex min-h-0 flex-1 flex-col">
        <div
          className={`flex items-center gap-2 border-y border-line px-3 py-1.5 ${isArchive ? 'bg-brand/10' : 'bg-danger/10'}`}
        >
          <span className={`size-2 shrink-0 rounded-full ${dotClass}`} />
          <span className={`font-mono text-[11px] tracking-widest ${labelClass}`}>{title}</span>
          <span className="font-mono text-[10px] text-ink-dim">
            {lines.length} {lines.length === 1 ? 'sender' : 'senders'}
          </span>
          <span className="ml-auto font-mono text-sm">{count(lines)}</span>
        </div>
        <ul className="min-h-0 flex-1 overflow-y-auto">
          {lines.length > 0 ? (
            lines.map((line) => {
              const key = line.key + ':' + action
              const active = pinned === key || hover === key
              return (
                <li
                  key={line.key}
                  className={`flex items-center gap-2 px-2 py-1 ${active ? 'bg-panel2' : ''}`}
                  onMouseEnter={(event) => peek(event, key)}
                  onMouseLeave={() => setHover(null)}
                >
                  <button
                    type="button"
                    className="flex min-w-0 flex-1 cursor-pointer items-center gap-2 text-left"
                    aria-pressed={pinned === key}
                    onClick={(event) => pinPeek(event.currentTarget, key)}
                  >
                    {pinned === key && (
                      <span
                        className="shrink-0 font-mono text-[10px] text-brand"
                        role="img"
                        aria-label="Pinned"
                        title="Pinned"
                      >
                        ◆
                      </span>
                    )}
                    <span className="flex h-3 w-12 shrink-0 items-center gap-px">
                      {Array.from({ length: Math.min(line.msgs.length, 9) }).map((_, index) => (
                        <span
                          key={index}
                          className={`h-3 w-1 shrink-0 rounded-[1px] ${dotClass} ${active ? 'opacity-100' : 'opacity-60'}`}
                        />
                      ))}
                      {line.msgs.length > 9 && (
                        <span className={`ml-0.5 font-mono text-[8px] ${labelClass}`}>+</span>
                      )}
                    </span>
                    <span className="min-w-0 flex-1 truncate text-[11px]">
                      {senderName(line.from)}
                    </span>
                    {line.byRule && (
                      <span className="shrink-0 font-mono text-[8px] text-ink-dim">RULE</span>
                    )}
                    <span className="w-5 shrink-0 text-right font-mono text-[10px]">
                      {line.msgs.length}
                    </span>
                  </button>
                  <button
                    type="button"
                    className="shrink-0 rounded px-1.5 py-0.5 font-mono text-[10px] text-ink-dim hover:bg-panel3 hover:text-ink"
                    title={`Put ${line.msgs.length} back in the Inbox`}
                    onClick={() => {
                      if (pinned === key) setPinned(null)
                      onunmark(line.msgs.map((message) => message.id))
                    }}
                  >
                    ↩
                  </button>
                </li>
              )
            })
          ) : (
            <li className="px-3 py-5 text-center font-mono text-[10px] text-ink-dim">empty</li>
          )}
        </ul>
      </div>
    )
  }

  return (
    <aside className="relative flex h-full min-h-0 flex-col bg-panel">
      <div className="flex items-baseline gap-2 px-3 py-2">
        <span className="font-mono text-[11px] tracking-widest text-ink-dim">STAGING</span>
        <span className="font-mono text-[11px] text-ink-dim">{total} pending</span>
        <button
          className="ml-auto font-mono text-[10px] text-ink-dim hover:text-ink disabled:opacity-30"
          disabled={total === 0}
          onClick={onunmarkall}
        >
          empty both
        </button>
      </div>
      {renderBin('TO ARCHIVE', 'archive', archive)}
      {renderBin('TO DELETE', 'trash', trash)}
      <div className="border-t border-line p-3">
        <button
          className="w-full rounded-md bg-brand py-2.5 font-mono text-[11px] text-on-brand disabled:opacity-30"
          disabled={total === 0 || busy}
          onClick={onapply}
        >
          {busy ? 'APPLYING…' : `APPLY — ${count(archive)} ARCHIVE, ${count(trash)} DELETE`}
        </button>
      </div>
      {hovered && (
        <div
          className="fixed right-[310px] z-30 max-h-[calc(100vh-16px)] w-80 overflow-hidden rounded-lg border border-line bg-panel p-3 shadow-2xl"
          style={{
            top: Math.min(
              Math.max(hoverY - 8, 8),
              Math.max(window.innerHeight - (peekExpanded ? 400 : 220), 8)
            )
          }}
        >
          <div className="flex items-baseline gap-2">
            <span className="min-w-0 truncate text-sm font-semibold">
              {senderName(hovered.from)}
            </span>
            <span
              className={`font-mono text-[10px] ${marks[hovered.msgs[0].id] === 'archive' ? 'text-brand' : 'text-danger'}`}
            >
              {marks[hovered.msgs[0].id] === 'archive' ? 'archive' : 'delete'}
            </span>
            <span className="ml-auto shrink-0 font-mono text-[10px] text-ink-dim">
              {hovered.msgs.length}
            </span>
            <button
              type="button"
              className="shrink-0 rounded border border-line px-1.5 py-0.5 font-mono text-[9px] text-ink-dim hover:bg-panel3 hover:text-ink"
              aria-label="Close sender peek"
              title="Close"
              onClick={closePeek}
            >
              CLOSE
            </button>
          </div>
          <div className="mt-0.5 truncate font-mono text-[10px] text-ink-dim">
            {senderAddr(hovered.from)}
          </div>
          <ul
            className={`mt-2 max-h-64 space-y-1 border-t border-line pt-2 ${peekExpanded ? 'overflow-y-auto pr-1' : ''}`}
          >
            {(peekExpanded ? hovered.msgs : hovered.msgs.slice(0, 6)).map((message) => (
              <li key={message.id}>
                <div className="truncate text-xs">{message.subject}</div>
                <div className="truncate text-[11px] text-ink-dim">{message.snippet}</div>
              </li>
            ))}
            {hovered.msgs.length > 6 && !peekExpanded && (
              <li>
                <button
                  type="button"
                  className="font-mono text-[10px] text-ink-dim underline decoration-dotted underline-offset-2 hover:text-ink"
                  onClick={() => setPeekExpanded(true)}
                >
                  +{hovered.msgs.length - 6} more
                </button>
              </li>
            )}
          </ul>
        </div>
      )}
    </aside>
  )
}

// src/renderer/src/components/StagingBins.svelte
<script lang="ts">
  // Staging: two named bins so Archive and Delete never mix, one dense line per sender
  // (bar length = count), a hover peek that tracks the line, and an explicit put-back
  // control. Click a line to keep its peek open while inspecting the messages.
  import type { EmailMsg, MarkAction, MarkedItem } from '../types'
  import { senderAddr, senderName } from '../lib/sender'

  type Line = { key: string; from: string; msgs: EmailMsg[]; byRule: boolean }

  let {
    emails,
    marks,
    rules,
    busy = false,
    onunmark,
    onunmarkall,
    onapply
  }: {
    emails: EmailMsg[]
    marks: Record<string, MarkAction>
    rules: MarkedItem[]
    busy?: boolean
    onunmark: (ids: string[]) => void
    onunmarkall: () => void
    onapply: () => void
  } = $props()

  const ruleFor = (from: string): MarkedItem | undefined =>
    rules.find((r) => r.from.trim() && from.toLowerCase().includes(r.from.trim().toLowerCase()))

  const linesFor = (action: MarkAction): Line[] => {
    const by = new Map<string, Line>()
    for (const m of emails) {
      if (marks[m.id] !== action) continue
      const key = senderAddr(m.from)
      if (!by.has(key)) by.set(key, { key, from: m.from, msgs: [], byRule: !!ruleFor(m.from) })
      by.get(key)!.msgs.push(m)
    }
    return [...by.values()].sort((a, b) => b.msgs.length - a.msgs.length)
  }

  const archive = $derived(linesFor('archive'))
  const trash = $derived(linesFor('trash'))
  const total = $derived(Object.keys(marks).length)
  const count = (ls: Line[]): number => ls.reduce((n, l) => n + l.msgs.length, 0)

  let hover = $state<string | null>(null)
  let pinned = $state<string | null>(null)
  let peekExpanded = $state(false)
  let hoverY = $state(0)
  const hovered = $derived.by(() => {
    const lines = [...archive, ...trash]
    const pinnedLine = pinned
      ? lines.find((l) => l.key + ':' + marks[l.msgs[0].id] === pinned)
      : undefined
    const key = pinnedLine ? pinned : hover
    return lines.find((l) => l.key + ':' + marks[l.msgs[0].id] === key)
  })

  function peek(e: MouseEvent, key: string): void {
    if (!pinned && hover !== key) peekExpanded = false
    hover = key
    if (!pinned) hoverY = (e.currentTarget as HTMLElement).getBoundingClientRect().top
  }

  function pinPeek(element: HTMLElement, key: string): void {
    hover = key
    hoverY = element.getBoundingClientRect().top
    if (pinned === key) {
      pinned = null
      peekExpanded = false
      return
    }
    pinned = key
    peekExpanded = false
  }

  function closePeek(): void {
    pinned = null
    hover = null
    peekExpanded = false
  }
</script>

<aside class="relative flex min-h-0 flex-col bg-panel">
  <div class="flex items-baseline gap-2 px-3 py-2">
    <span class="font-mono text-[11px] tracking-widest text-ink-dim">STAGING</span>
    <span class="font-mono text-[11px] text-ink-dim">{total} pending</span>
    <button
      class="ml-auto font-mono text-[10px] text-ink-dim hover:text-ink disabled:opacity-30"
      disabled={total === 0}
      onclick={onunmarkall}>empty both</button
    >
  </div>

  {#snippet bin(title: string, action: MarkAction, ls: Line[])}
    <!-- Tailwind scans literal strings, so the tone classes are spelled out. -->
    {@const isArchive = action === 'archive'}
    {@const dot = isArchive ? 'bg-brand' : 'bg-danger'}
    {@const label = isArchive ? 'text-brand' : 'text-danger'}
    <div class="flex min-h-0 flex-1 flex-col">
      <div
        class="flex items-center gap-2 border-y border-line px-3 py-1.5 {action === 'archive'
          ? 'bg-brand/10'
          : 'bg-danger/10'}"
      >
        <span class="size-2 shrink-0 rounded-full {dot}"></span>
        <span class="font-mono text-[11px] tracking-widest {label}">{title}</span>
        <span class="font-mono text-[10px] text-ink-dim">
          {ls.length}
          {ls.length === 1 ? 'sender' : 'senders'}
        </span>
        <span class="ml-auto font-mono text-sm">{count(ls)}</span>
      </div>

      <ul class="min-h-0 flex-1 overflow-y-auto">
        {#each ls as l (l.key)}
          {@const k = l.key + ':' + action}
          <li
            class="flex items-center gap-2 px-2 py-1 {pinned === k || hover === k
              ? 'bg-panel2'
              : ''}"
            onmouseenter={(e) => peek(e, k)}
            onmouseleave={() => (hover = null)}
          >
            <button
              type="button"
              class="flex min-w-0 flex-1 cursor-pointer items-center gap-2 text-left"
              aria-pressed={pinned === k}
              onclick={(e) => pinPeek(e.currentTarget as HTMLElement, k)}
            >
              {#if pinned === k}
                <span class="shrink-0 font-mono text-[10px] text-brand" role="img" aria-label="Pinned" title="Pinned">◆</span>
              {/if}
              <span class="flex h-3 w-12 shrink-0 items-center gap-px">
                {#each { length: Math.min(l.msgs.length, 9) } as _}
                  <span
                    class="h-3 w-1 shrink-0 rounded-[1px] {dot} {pinned === k || hover === k
                      ? 'opacity-100'
                      : 'opacity-60'}"
                  ></span>
                {/each}
                {#if l.msgs.length > 9}
                  <span class="ml-0.5 font-mono text-[8px] {label}">+</span>
                {/if}
              </span>
              <span class="min-w-0 flex-1 truncate text-[11px]">{senderName(l.from)}</span>
              {#if l.byRule}
                <span class="shrink-0 font-mono text-[8px] text-ink-dim">RULE</span>
              {/if}
              <span class="w-5 shrink-0 text-right font-mono text-[10px]">{l.msgs.length}</span>
            </button>
            <button
              class="shrink-0 rounded px-1.5 py-0.5 font-mono text-[10px] text-ink-dim hover:bg-panel3 hover:text-ink"
              title="Put {l.msgs.length} back in the Inbox"
              onclick={() => {
                if (pinned === k) pinned = null
                onunmark(l.msgs.map((m) => m.id))
              }}>↩</button
            >
          </li>
        {:else}
          <li class="px-3 py-5 text-center font-mono text-[10px] text-ink-dim">empty</li>
        {/each}
      </ul>
    </div>
  {/snippet}

  {@render bin('TO ARCHIVE', 'archive', archive)}
  {@render bin('TO DELETE', 'trash', trash)}

  <div class="border-t border-line p-3">
    <button
      class="w-full rounded-md bg-brand py-2.5 font-mono text-[11px] text-on-brand disabled:opacity-30"
      disabled={total === 0 || busy}
      onclick={onapply}
    >
      {busy ? 'APPLYING…' : `APPLY — ${count(archive)} ARCHIVE, ${count(trash)} DELETE`}
    </button>
  </div>

  {#if hovered}
    {@const a = marks[hovered.msgs[0].id]}
    <div
      class="fixed right-[310px] z-30 max-h-[calc(100vh-16px)] w-80 overflow-hidden rounded-lg border border-line bg-panel p-3 shadow-2xl"
      style="top:{Math.min(Math.max(hoverY - 8, 8), Math.max(window.innerHeight - (peekExpanded ? 400 : 220), 8))}px"
    >
      <div class="flex items-baseline gap-2">
        <span class="min-w-0 truncate text-sm font-semibold">{senderName(hovered.from)}</span>
        <span class="font-mono text-[10px] {a === 'archive' ? 'text-brand' : 'text-danger'}"
          >{a === 'archive' ? 'archive' : 'delete'}</span
        >
        <span class="ml-auto shrink-0 font-mono text-[10px] text-ink-dim">{hovered.msgs.length}</span>
        <button
          class="shrink-0 rounded border border-line px-1.5 py-0.5 font-mono text-[9px] text-ink-dim hover:bg-panel3 hover:text-ink"
          aria-label="Close sender peek"
          title="Close"
          onclick={closePeek}>CLOSE</button
        >
      </div>
      <div class="mt-0.5 truncate font-mono text-[10px] text-ink-dim">
        {senderAddr(hovered.from)}
      </div>
      <ul
        class="mt-2 max-h-64 space-y-1 border-t border-line pt-2 {peekExpanded
          ? 'overflow-y-auto pr-1'
          : ''}"
      >
        {#each (peekExpanded ? hovered.msgs : hovered.msgs.slice(0, 6)) as m (m.id)}
          <li>
            <div class="truncate text-xs">{m.subject}</div>
            <div class="truncate text-[11px] text-ink-dim">{m.snippet}</div>
          </li>
        {/each}
        {#if hovered.msgs.length > 6 && !peekExpanded}
          <li>
            <button
              type="button"
              class="font-mono text-[10px] text-ink-dim underline decoration-dotted underline-offset-2 hover:text-ink"
              onclick={() => (peekExpanded = true)}
            >+{hovered.msgs.length - 6} more</button>
          </li>
        {/if}
      </ul>
    </div>
  {/if}
</aside>
