// src/renderer/src/prototype/variants/V10FocusQueue.svelte
<script lang="ts">
  // PROTOTYPE — Variant 10: Focus Queue.
  // Premise: triage is a session, not a screen you live in. Five at a time, a visible
  // finish line, and one confirmation at the end of each batch.
  import type { MarkAction } from '../../types'
  import { ws } from '../store.svelte'
  import { senderName } from '../fixtures'

  const BATCH = 5
  let batchStart = $state(0)
  let started = $state(false)

  const untouched = $derived(ws.inbox.filter((m) => !ws.marks[m.id]))
  const batch = $derived(untouched.slice(0, BATCH))
  const decided = $derived(batch.filter((m) => ws.marks[m.id]).length)
  const total = $derived(ws.inbox.length)
  const left = $derived(untouched.length)

  function decide(id: string, action: MarkAction): void {
    ws.marks[id] = action
  }
  function commitBatch(): void {
    ws.applyAll()
    batchStart += BATCH
  }
</script>

<div class="flex h-full flex-col items-center overflow-y-auto">
  {#if !started}
    <div class="m-auto max-w-md text-center">
      <div class="font-mono text-xs tracking-widest text-brand">TRIAGE SESSION</div>
      <h1 class="mt-4 text-4xl font-light">{total} messages</h1>
      <p class="mt-4 text-sm leading-relaxed text-accent-dim">
        Five at a time. Decide archive or delete for each, then send the batch to Gmail.
        Roughly {Math.ceil(total / BATCH)} rounds.
      </p>
      <button
        class="mt-8 rounded-full bg-brand px-8 py-3 font-mono text-sm text-black"
        onclick={() => (started = true)}>START</button
      >
      <button
        class="mt-3 block w-full font-mono text-xs text-accent-dim hover:text-accent"
        onclick={() => { ws.runQuery(); started = true }}>apply my sender rules first</button
      >
    </div>
  {:else if left === 0}
    <div class="m-auto text-center">
      <div class="text-5xl">Inbox zero</div>
      <div class="mt-4 font-mono text-xs text-accent-dim">
        {ws.applied.length} messages sent to Gmail this session
      </div>
      <button
        class="mt-8 rounded-full border border-white/15 px-6 py-2 font-mono text-xs hover:bg-surface-hover"
        onclick={() => { ws.reset(); started = false; batchStart = 0 }}>run again</button
      >
    </div>
  {:else}
    <div class="w-full max-w-3xl px-6 pt-10">
      <div class="flex items-baseline gap-3">
        <span class="font-mono text-xs tracking-widest text-accent-dim">ROUND {batchStart / BATCH + 1}</span>
        <span class="ml-auto font-mono text-xs text-accent-dim">{left} left of {total}</span>
      </div>
      <div class="mt-2 flex h-1.5 gap-1">
        {#each { length: Math.ceil(total / BATCH) } as _, i}
          <div
            class="flex-1 rounded-full {i < batchStart / BATCH
              ? 'bg-brand'
              : i === batchStart / BATCH
                ? 'bg-brand/40'
                : 'bg-surface'}"
          ></div>
        {/each}
      </div>

      <ul class="mt-8 space-y-3">
        {#each batch as m (m.id)}
          {@const a = ws.marks[m.id]}
          <li
            class="rounded-xl border p-4 transition-colors {a === 'archive'
              ? 'border-brand/50 bg-brand/5'
              : a === 'trash'
                ? 'border-danger/50 bg-danger/5'
                : 'border-white/8 bg-surface'}"
          >
            <div class="flex items-baseline gap-2">
              <span class="text-sm font-semibold">{senderName(m.from)}</span>
              <span class="ml-auto font-mono text-[10px] text-accent-dim">{m.date}</span>
            </div>
            <div class="mt-1 text-[15px]">{m.subject}</div>
            <div class="mt-1 line-clamp-2 text-xs text-accent-dim">{m.snippet}</div>
            <div class="mt-3 flex gap-2">
              <button
                class="flex-1 rounded-lg py-2 font-mono text-[11px] {a === 'archive'
                  ? 'bg-brand text-black'
                  : 'bg-surface-hover hover:bg-surface-active'}"
                onclick={() => decide(m.id, 'archive')}>ARCHIVE</button
              >
              <button
                class="flex-1 rounded-lg py-2 font-mono text-[11px] {a === 'trash'
                  ? 'bg-danger text-black'
                  : 'bg-surface-hover hover:bg-surface-active'}"
                onclick={() => decide(m.id, 'trash')}>DELETE</button
              >
              <button
                class="rounded-lg px-4 py-2 font-mono text-[11px] text-accent-dim hover:text-accent"
                onclick={() => ws.unmark([m.id])}>KEEP</button
              >
            </div>
          </li>
        {/each}
      </ul>

      <div class="sticky bottom-0 mt-6 flex items-center gap-3 bg-base py-4 pb-16">
        <span class="font-mono text-xs text-accent-dim">{decided} of {batch.length} decided</span>
        <button
          class="ml-auto rounded-full bg-brand px-6 py-2.5 font-mono text-xs text-black disabled:opacity-30"
          disabled={ws.markedCount === 0}
          onclick={commitBatch}>SEND BATCH TO GMAIL ({ws.markedCount})</button
        >
      </div>
    </div>
  {/if}
</div>

// src/renderer/src/prototype/variants/V10FocusQueue.tsx
// PROTOTYPE — Variant 10: Focus Queue.
// Premise: triage is a session, not a screen you live in. Five at a time, a visible
// finish line, and one confirmation at the end of each batch.
import { useState } from 'react'
import type { EmailMsg, MarkAction } from '../../types'
import { senderName } from '../fixtures'
import { useWorkspace } from '../store'

const BATCH = 5

export default function V10FocusQueue() {
  const ws = useWorkspace()
  const [queue, setQueue] = useState<string[]>(() => ws.inbox.map((message) => message.id))
  const [started, setStarted] = useState(false)
  const [round, setRound] = useState(0)
  const total = ws.inbox.length
  const batch = queue
    .slice(0, BATCH)
    .map((id) => ws.inbox.find((message) => message.id === id))
    .filter((message): message is EmailMsg => Boolean(message))
  const left = queue.length
  const decided = batch.filter((message) => Boolean(ws.marks[message.id])).length

  const decide = (id: string, action: MarkAction) => ws.mark([id], action)
  const keep = (id: string) => setQueue((current) => current.filter((item) => item !== id))
  const commitBatch = () => {
    const markedIds = new Set(Object.keys(ws.marks))
    ws.applyAll()
    setQueue((current) => current.filter((id) => !markedIds.has(id)))
    setRound((current) => current + 1)
  }
  const startWithRules = () => {
    ws.runQuery()
    setStarted(true)
  }
  const runAgain = () => {
    ws.reset()
    setQueue(ws.inbox.map((message) => message.id))
    setStarted(false)
    setRound(0)
  }

  return (
    <div className="flex h-full flex-col items-center overflow-y-auto">
      {!started ? (
        <div className="m-auto max-w-md text-center">
          <div className="font-mono text-xs tracking-widest text-brand">TRIAGE SESSION</div>
          <h1 className="mt-4 text-4xl font-light">{total} messages</h1>
          <p className="mt-4 text-sm leading-relaxed text-accent-dim">
            Five at a time. Decide archive or delete for each, then send the batch to Gmail. Roughly{' '}
            {Math.ceil(total / BATCH)} rounds.
          </p>
          <button
            className="mt-8 rounded-full bg-brand px-8 py-3 font-mono text-sm text-black"
            onClick={() => setStarted(true)}
          >
            START
          </button>
          <button
            className="mt-3 block w-full font-mono text-xs text-accent-dim hover:text-accent"
            onClick={startWithRules}
          >
            apply my sender rules first
          </button>
        </div>
      ) : left === 0 ? (
        <div className="m-auto text-center">
          <div className="text-5xl">Inbox zero</div>
          <div className="mt-4 font-mono text-xs text-accent-dim">
            {ws.applied.length} messages sent to Gmail this session
          </div>
          <button
            className="mt-8 rounded-full border border-white/15 px-6 py-2 font-mono text-xs hover:bg-surface-hover"
            onClick={runAgain}
          >
            run again
          </button>
        </div>
      ) : (
        <div className="w-full max-w-3xl px-6 pb-16 pt-10">
          <div className="flex items-baseline gap-3">
            <span className="font-mono text-xs tracking-widest text-accent-dim">
              ROUND {round + 1}
            </span>
            <span className="ml-auto font-mono text-xs text-accent-dim">
              {left} left of {total}
            </span>
          </div>
          <div className="mt-2 flex h-1.5 gap-1">
            {Array.from({ length: Math.ceil(total / BATCH) }).map((_, index) => (
              <div
                key={index}
                className={`flex-1 rounded-full ${index < round ? 'bg-brand' : index === round ? 'bg-brand/40' : 'bg-surface'}`}
              />
            ))}
          </div>

          <ul className="mt-8 space-y-3">
            {batch.map((message) => {
              const action = ws.marks[message.id]
              return (
                <li
                  key={message.id}
                  className={`rounded-xl border p-4 transition-colors ${action === 'archive' ? 'border-brand/50 bg-brand/5' : action === 'trash' ? 'border-danger/50 bg-danger/5' : 'border-white/8 bg-surface'}`}
                >
                  <div className="flex items-baseline gap-2">
                    <span className="text-sm font-semibold">{senderName(message.from)}</span>
                    <span className="ml-auto font-mono text-[10px] text-accent-dim">
                      {message.date}
                    </span>
                  </div>
                  <div className="mt-1 text-[15px]">{message.subject}</div>
                  <div className="mt-1 line-clamp-2 text-xs text-accent-dim">{message.snippet}</div>
                  <div className="mt-3 flex gap-2">
                    <button
                      className={`flex-1 rounded-lg py-2 font-mono text-[11px] ${action === 'archive' ? 'bg-brand text-black' : 'bg-surface-hover hover:bg-surface-active'}`}
                      onClick={() => decide(message.id, 'archive')}
                    >
                      ARCHIVE
                    </button>
                    <button
                      className={`flex-1 rounded-lg py-2 font-mono text-[11px] ${action === 'trash' ? 'bg-danger text-black' : 'bg-surface-hover hover:bg-surface-active'}`}
                      onClick={() => decide(message.id, 'trash')}
                    >
                      DELETE
                    </button>
                    <button
                      className="rounded-lg px-4 py-2 font-mono text-[11px] text-accent-dim hover:text-accent"
                      onClick={() => keep(message.id)}
                    >
                      KEEP
                    </button>
                  </div>
                </li>
              )
            })}
          </ul>

          <div className="sticky bottom-0 mt-6 flex items-center gap-3 bg-base py-4">
            <span className="font-mono text-xs text-accent-dim">
              {decided} of {batch.length} decided
            </span>
            <button
              className="ml-auto rounded-full bg-brand px-6 py-2.5 font-mono text-xs text-black disabled:opacity-30"
              disabled={ws.markedCount === 0}
              onClick={commitBatch}
            >
              SEND BATCH TO GMAIL ({ws.markedCount})
            </button>
          </div>
        </div>
      )}
    </div>
  )
}
